#!/usr/bin/env node
// Regenerates THIRD_PARTY_NOTICES.md from the production dependencies of the
// workspace (`pnpm licenses list --json --prod`) plus the hand-written section
// in scripts/notices/non-npm.md.
//
// Usage: node scripts/generate-notices.mjs [--check]
//   --check   do not write; exit 1 if THIRD_PARTY_NOTICES.md is out of date

import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = join(root, 'THIRD_PARTY_NOTICES.md');
const workspace = /^@memozi\//;

const LICENSE_FILE = /^(licen[cs]e|copying)([-._].*)?$/i;
const NOTICE_FILE = /^notice(\.(md|txt))?$/i;

function readLicenseFiles(dir) {
  if (!existsSync(dir)) return { license: '', notice: '' };
  const files = readdirSync(dir).sort();
  // Prefer LICENSE over COPYING, and the shortest name (LICENSE over LICENSE-docs).
  const licenseFile = files
    .filter((f) => LICENSE_FILE.test(f))
    .sort(
      (a, b) => Number(/^copying/i.test(a)) - Number(/^copying/i.test(b)) || a.length - b.length,
    )[0];
  const noticeFile = files.find((f) => NOTICE_FILE.test(f));
  const read = (f) =>
    f
      ? readFileSync(join(dir, f), 'utf8')
          .replace(/\r\n?/g, '\n')
          .replace(/[ \t]+$/gm, '')
          .trim()
      : '';
  return { license: read(licenseFile), notice: read(noticeFile) };
}

function fence(text) {
  const longest = Math.max(2, ...(text.match(/`+/g) ?? []).map((run) => run.length));
  const ticks = '`'.repeat(longest + 1);
  return `${ticks}text\n${text}\n${ticks}`;
}

const report = JSON.parse(
  execFileSync('pnpm', ['licenses', 'list', '--json', '--prod'], {
    cwd: root,
    encoding: 'utf8',
    maxBuffer: 256 * 1024 * 1024,
    stdio: ['ignore', 'pipe', 'inherit'],
  }),
);

// One entry per package version; identical texts are grouped to keep the file short.
const groups = new Map();
for (const pkg of Object.values(report).flat()) {
  if (workspace.test(pkg.name)) continue;
  pkg.versions.forEach((version, i) => {
    const { license, notice } = readLicenseFiles(pkg.paths[i] ?? pkg.paths[0]);
    const body =
      (license ||
        `No license file in the package. Declared license: ${pkg.license}.` +
          (pkg.homepage ? `\nHomepage: ${pkg.homepage}` : '')) +
      (notice ? `\n\n--- NOTICE ---\n\n${notice}` : '');
    const key = `${pkg.license}\n${body}`;
    if (!groups.has(key)) groups.set(key, { spdx: pkg.license, body, packages: [] });
    groups.get(key).packages.push(`${pkg.name}@${version}`);
  });
}

const sections = [...groups.values()]
  .map((g) => ({ ...g, packages: g.packages.sort() }))
  .sort((a, b) => a.packages[0].localeCompare(b.packages[0]));

const packageCount = sections.reduce((n, g) => n + g.packages.length, 0);
const nonNpm = readFileSync(join(root, 'scripts/notices/non-npm.md'), 'utf8').trim();

const output = [
  '# Third-party notices',
  '',
  'MemoZi is licensed under AGPL-3.0-or-later (see [`LICENSE`](LICENSE)). It includes or uses the',
  'third-party components listed below, each under its own license.',
  '',
  '<!-- Generated by `pnpm licenses:notices` (scripts/generate-notices.mjs). Do not edit by hand:',
  'change scripts/notices/non-npm.md for the section below and rerun the script. -->',
  '',
  nonNpm,
  '',
  '## npm production dependencies',
  '',
  `${packageCount} packages from \`pnpm licenses list --prod\` across the backend, frontend and shared`,
  'workspaces. Development-only tools are not distributed and are not listed. Packages with the same',
  'license text are grouped.',
  '',
  ...sections.flatMap((g) => [
    `### ${g.packages.join(', ')}`,
    '',
    `License: ${g.spdx}`,
    '',
    fence(g.body),
    '',
  ]),
].join('\n');

if (process.argv.includes('--check')) {
  const current = existsSync(outputPath) ? readFileSync(outputPath, 'utf8') : '';
  if (current !== output) {
    console.error('THIRD_PARTY_NOTICES.md is out of date. Run `pnpm licenses:notices`.');
    process.exit(1);
  }
  console.log('THIRD_PARTY_NOTICES.md is up to date.');
} else {
  writeFileSync(outputPath, output);
  console.log(
    `Wrote THIRD_PARTY_NOTICES.md (${packageCount} packages, ${sections.length} sections).`,
  );
}
